Implement stem and leaf tables
jasp-stats/jaspDescriptives pull request #2
Opened 2020-10-27 14:50 UTC by vandenman

Fixes one part of jasp-stats/jasp-issues#684 and implements stem and leaf tables. Dot plots will be implemented in another PR.

Sequel of https://github.com/jasp-stats/jasp-desktop/pull/4273/files

Example:

![image](https://user-images.githubusercontent.com/21319932/92482611-18436c80-f1e8-11ea-80a5-47641c0bfe25.png)

2020-11-12 12:06 UTC, TimKDJ requested changes
So the general functionality seems fine. I feel like the use of these tables quickly diminishes when you have a big spread in your values, but I guess they're not really meant for that situation?

2020-11-12 13:35 UTC, vandenman commented on inst/qml/Descriptives.qml
> +		name	: "stemAndLeaf";
just did, let me know if this is what you had in mind!

2020-11-12 13:53 UTC, vandenman commented
> I feel like the use of these tables quickly diminishes when you have a big spread in your values, but I guess they're not really meant for that situation?

I think the main use is educational, considering I've never actually used this or seen it in lectures. 

However, according to https://github.com/jasp-stats/jasp-issues/issues/684#issue-601463536 it's actually quite important:

> In his book "The Grammar of Graphics", Wilkinson (2005, p. 137) suggests that:
> Statistics texts and statistical packages that recommend the histogram as the graphical starting point for a data analysis are giving bad advice. The same goes for kernel density estimates. These are appropriate second stages for graphical data analysis. The best starting point for getting a sense of the distribution of a variable is a tally, stem-and-leaf, or a dot plot. A dot plot is a special case of a tally (perhaps best thought of as a delta-neighborhood tally). Once we see that the data are not granular, we may move on to a histogram or kernel density, which smooths the data more than a dot plot.

So it seems that some people value this a lot.


Concerning:

> I was also thinking (but feel free to disregard, I've never used a stem-and-leaf, this is based on some googling):
> 
>It could be good to add information about whether we cut or round values (like here: archive.org/details/exploratorydataa00tuke_0/page/8/mode/2up?q=stem)
>Adding Stem unit (and Leaf unit?) would make it a bit more intuitive what the values are (like here: mathworld.wolfram.com/Stem-and-LeafDiagram.html)

R doesn't provide that information. We could deviate from what R does and really dive into the literature, but I'm not sure if that's worth the effort. We'd probably have to roll our own implementation of this as well.

2020-11-12 13:53 UTC, vandenman commented on R/descriptives.R
> +  tb$addFootnote(footnote)
good point, I've now translated the footnote.

2020-11-12 13:54 UTC, vandenman commented on R/descriptives.R
> +  other <- temp[4:(length(temp) - 1L)]
we can now, I've added some checks for corner cases and show error messages if that happens.

2020-11-12 13:54 UTC, vandenman commented on R/descriptives.R
> +      subcontainer$dependOn(optionContainsValue = list(variables = var))
This was by mistake :)

2020-11-12 14:27 UTC, TimKDJ commented on inst/qml/Descriptives.qml
> +		name	: "stemAndLeaf";
Yeah this looks good

2020-11-12 14:27 UTC, TimKDJ commented on R/descriptives.R
> +      jaspResults[["scatterPlots"]]$position <- 11
Think you missed this one

2020-11-12 14:28 UTC, TimKDJ commented
Can you add a unit test?

2020-11-17 10:50 UTC, TimKDJ approved these changes

2020-11-17 10:50 UTC, merged