"custom plots" tab is now more intuitive and consistent
jasp-stats/jaspDescriptives pull request #242
Opened 2024-02-16 15:41 UTC by JohnnyDoorn

2024-02-16 15:46 UTC, boutinb requested changes

2024-02-16 15:46 UTC, boutinb commented on inst/qml/Descriptives.qml
> +					label: qsTr("")
no qsTr function with empty string

2024-02-16 15:46 UTC, boutinb commented on inst/qml/Descriptives.qml
> +					label: 				qsTr("")
no qsTr function with empty string

2024-02-19 12:11 UTC, JohnnyDoorn commented
@boutinb @vandenman 
I removed those empty qstr's, and added an option to the custom density plots, such that histograms are also available there. I also tweaked the transparency option to also only show when it actually has a use.

2024-02-19 12:30 UTC, boutinb approved these changes

2024-02-19 12:31 UTC, merged