Chi square method to calculate var and std dev CIs
jasp-stats/jaspDescriptives pull request #312
Opened 2024-09-20 14:06 UTC by JTPetter

Implemented chi-squared method to calculate confidence intervals for std. dev. and variance in descriptives.

2024-09-22 17:59 UTC, vandenman requested changes

2024-09-22 17:59 UTC, vandenman commented on inst/qml/Descriptives.qml
> +					info: qsTr("How should the confidence interval be computed? By default, we use a chi-sqaured model. The alternative option is `Bootstrap`")
```suggestion
					info: qsTr("How should the confidence interval be computed? By default, we use a chi-squared model. The alternative option is `Bootstrap`")
```
same below for variances.

I wonder if "Chi-squared model" is the right name. Perhaps we should just call this the "analytical" solution or "normal" approach and then leave the details for the help file?

2024-09-22 17:59 UTC, vandenman commented on R/descriptives.R
> +    upperBound <- sqrt((n - 1) * sigma^2 / chiSqLower)
```suggestion
    CIs <- stats::quantile(sds, probs = percentiles)
    lowerBound <- CIs[1]
    upperBound <- CIs[2]
  } else if (options[["sdCiMethod"]] == "chiSquaredModel") {
    sigma <- stats::sd(data)
    n <- length(data)
    alpha <- 1 - ciWidth
    chiSqLower <- stats::qchisq(alpha / 2, df = n - 1)
    chiSqUpper <- stats::qchisq(1 - alpha / 2, df = n - 1)
    lowerBound <- sqrt((n - 1) * sigma^2 / chiSqUpper)
    upperBound <- sqrt((n - 1) * sigma^2 / chiSqLower)
```
a (Wikipedia) reference to the equations as a comment would also be nice.

2024-09-22 17:59 UTC, vandenman commented on R/descriptives.R
> +    chiSqUpper <- qchisq(1 - alpha / 2, df = n - 1)
```suggestion
    CIs <- stats::quantile(variances, probs = percentiles)
    lowerBound <- CIs[1]
    upperBound <- CIs[2]
  } else if (options[["varianceCiMethod"]] == "chiSquaredModel") {
    sigma <- stats::sd(data)
    n <- length(data)
    alpha <- 1 - ciWidth
    chiSqLower <- stats::qchisq(alpha / 2, df = n - 1)
    chiSqUpper <- stats::qchisq(1 - alpha / 2, df = n - 1)
```

2024-09-26 12:25 UTC, JTPetter commented
@vandenman Thank you, I have addressed your feedback.

2024-10-01 06:56 UTC, vandenman requested changes
Looks good. Could you also add a file called `NEWS.md` and list as a new feature? Something like

- new feature: analytic confidence intervals for standard deviation and variance (PR: #312).

See for example https://github.com/jasp-stats/jaspReliability/blob/master/NEWS.md

2024-10-01 06:56 UTC, vandenman commented on R/descriptives.R
> +# Formula for chi-square confidence intervals for std. dev. and variance found here: https://www.itl.nist.gov/div898/handbook/prc/section2/prc231.htm
This link gives a 503 service unavailable for me. Perhaps https://en.wikipedia.org/wiki/Standard_deviation#Confidence_interval_of_a_sampled_standard_deviation and https://en.wikipedia.org/wiki/Variance#Distribution_of_the_sample_variance are a better reference?

2024-10-03 09:16 UTC, vandenman approved these changes

2024-10-03 09:16 UTC, merged